### PR TITLE
Fixed Timed Export & Revert Export Settings

### PR DESCRIPTION
**Pull request by Ed-M72**
Remove the @master from requirements as it doesn't exist during build on Mac OS and create a UNIX script file for pushing dev builds.

### CODE REVIEW

**Comment by Ed-M72** [comment]
Timed export initially sets the SoC to 100% which stops it from exporting.  The user has to override it to a sensible %.  The current code only sets the Timed export mode if the SoC is 100%.

Removed the % check.

**Comment by britkat1980** [comment]
The code modified here will not change the action of Changing mode, it only determines what mode the invertor is in, based on a defined set of registers.
This commit will allow Timed Export to be assumed even if the reserve soc is not 100%.
This will not change the behaviour of the control action. That needs to be modified in the underlying library.
Does this change fix your issue?

**Comment by Ed-M72** [comment]
Yes it fixes the display issue of the Inverter mode showing "Unknown" rather than "Timed Export".  The Changing mode is a different issue and something else I need to look at.

**Comment by Ed-M72** [comment]
This is now ready for merge.  I took my local build file out of it, and moved the requirements file change to another pull request,

**Review by britkat1980 — APPROVED** [review]

**Pull request merged**
