### PR TITLE
Fixed Force Export & Force Resume

### PR DESCRIPTION
**Pull request by Ed-M72**
Add a new ENV variable to allow users to specify the number of enqueue retries.  This makes the force export/resume more reliable for multiple inverters.

Remove erroneous calls to set_shallow_reserve & setBatteryReserve from functions to stop force_export calls for  "Timed Export" and "Eco" from either setting the batteryReserve to something unexpected and then then having to reset it again after the call.  This change means that functions only deliver the changes they were named to do.

Added some clarification to register read values out of range during the above testing.

Fixed some spelling mistakes as I went along.

### CODE REVIEW

**Comment by britkat1980** [comment]
Question on the removal of setting shalow_charge for Eco mode. If you move from Eco (Paused) to Eco what is the behaviour? Looks like it will not change as nothing is resetting the battery reserve to a non-"100" value. Did you test this?

**Comment by Ed-M72** [comment]
Yep great point, and you are correct I hadn’t thought of that.  Checked in a further update to fix it.

On 16 Jun 2023, at 22:31, britkat1980 ***@***.***> wrote:



Question on the removal of setting shalow_charge for Eco mode. If you move from Eco (Paused) to Eco what is the behaviour? Looks like it will not change as nothing is resetting the battery reserve to a non-"100" value. Did you test this?

**Comment by britkat1980** [comment]
The code previously stores the battery reserve in a pkl so that we can restore it to where it should be after pausing. his should be used rather than an arbitrary value of 10%:
```
getSavedBatteryReservePercentage()
```
This is how it was working before. Was this not behaving as expected?

**Comment by Ed-M72** [comment]
Ah fantastic.  That is the one thing I couldn’t find.

On 17 Jun 2023, at 12:11, britkat1980 ***@***.***> wrote:



The code previously stores the battery reserve in a pkl so that we can restore it to where it should be after pausing. his should be used rather than an arbitrary value of 10%:

getSavedBatteryReservePercentage()


This is how it was working before. Was this not behaving as expected?

**Comment by britkat1980** [comment]
Thanks, all good to approve

**Pull request merged**
